# Generated by Django 5.1.2 on 2024-10-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="organiser",
            new_name="organizer",
        ),
    ]
